name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'markdown'
        destination_repo: 'Eurac-Research/ADO'
        destination_folder: 'public/markdown'
        user_email: 'thomas.iacopino@eurac.edu'
        user_name: 'tiacopino'
        commit_msg: '[GHA] Update the test files.'
